apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z3aiy8n7t-java-quarkus
  janus-idp.io/tekton: z3aiy8n7t-java-quarkus
  backstage.io/kubernetes-id: z3aiy8n7t-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: z3aiy8n7t-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
